---
#ansible-playbook artifactory-build.yml --extra-vars "version=23 destination=/tmp username=xyz password=xyz123"
- name: Copy War file from Artifactory
  hosts: localhost
  connection: localhost
  gather_facts: no
  roles:
    - download_build
